#!name=Panel
#!desc=信息面板

[Script]
SubInfo = type=generic,timeout=10,script-path=https://raw.githubusercontent.com/mieqq/mieqq/master/sub_info_panel.js,script-update-interval=0,argument=url=(订阅链接)&title=SubInfo&icon=bonjour&color=#a357d7&reset_day=1
网络信息 = type=generic,timeout=5,script-path=https://raw.githubusercontent.com/ventusyu/ventus/main/Panel/Net-info-panel.js
# > Netflix 解锁检测
nf_check = type=generic,timeout=5,script-path=https://gist.githubusercontent.com/Hyseen/b06e911a41036ebc36acf04ddebe7b9a/raw/nf_check.js
# > YouTube Premium 解锁检测
ytb_check = type=generic,timeout=5,script-path=https://gist.githubusercontent.com/Hyseen/5ae36a6a5cb5690b1f2bff4aa19c766f/raw/youtube_premium_check.js
# > Disney+ 解锁检测
disney_check = type=generic,timeout=5,script-path=https://gist.githubusercontent.com/Hyseen/729fc4c3ac28c3f2e7c4a832d81780f3/raw/disney_check.js
# > 配置重载
配置重载 = script-path=https://raw.githubusercontent.com/TributePaulWalker/Profiles/main/JavaScript/Surge/Profile-Reload.js,type=generic
# > DNS刷新
flushDNS = type=generic,timeout=5,script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/asset/flushDNS.js,argument=title=DNS FLush&icon=arrow.clockwise&color=#3d3d5b

[Panel]
SubInfo = script-name=SubInfo, update-interval=1800
网络信息 = script-name=网络信息,title=网络信息,content=请刷新,style=info,update-interval=60
nf_check = script-name=nf_check, title="Netflix 解锁检测", content="请刷新"
ytb_check = script-name=ytb_check, title="YouTube Premium 解锁检测"
disney_check = script-name=disney_check, title=Disney+ 解锁检测, content=请刷新
flushDNS = script-name=flushDNS,title=Flush DNS,content=请刷新,update-interval=600
配置重载 = title=配置重载,content=配置重载,style=info,script-name=配置重载,update-interval=-1
