#!name=信息面板
#!desc=信息面板

[Script]
TAG = type=generic,timeout=10,script-path=https://raw.githubusercontent.com/mieqq/mieqq/master/sub_info_panel.js,script-update-interval=0,argument=url=https://tagcontrol.xyz/api/v1/client/subscribe%3Ftoken%3D4c8d3c7d13d51cdd2f9357969549e111&title=SubInfo&icon=bonjour&color=#a357d7&reset_day=1
net-info-panel=type=generic,script-path=https://raw.githubusercontent.com/ventusyu/ventus/main/Panel/Net-info-panel.js
nf_check = type=generic,script-path=https://gist.githubusercontent.com/Hyseen/b06e911a41036ebc36acf04ddebe7b9a/raw/nf_check.js
ytb_check = type=generic,script-path=https://gist.githubusercontent.com/Hyseen/5ae36a6a5cb5690b1f2bff4aa19c766f/raw/youtube_premium_check.js
disney_check = type=generic,script-path=https://gist.githubusercontent.com/Hyseen/729fc4c3ac28c3f2e7c4a832d81780f3/raw/disney_check.js
flushDNS = type=generic,script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/asset/flushDNS.js,argument=title=DNS FLush&icon=arrow.clockwise&color=#3d3d5b

[Panel]
TAG = script-name=SubInfo, update-interval=1800
net-info-panel=title="网络状态",content="请刷新",style=info,script-name=net-info-panel
nf_check = script-name=nf_check, title="Netflix 解锁检测", content="请刷新"
ytb_check = script-name=ytb_check, title="YouTube Premium 解锁检测"
disney_check = script-name=disney_check, title=Disney+ 解锁检测, content=请刷新
flushDNS = script-name=flushDNS, title="Flush DNS", content="请刷新"
